export const GET_PRODUCT = "GET_PRODUCT";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const ORDER_BY_NAME = "ORDER_BY_NAME";
export const GET_BRANDS = "GET_BRANDS";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const ORDER_BY_PRICE_HL='ORDER_BY_PRICE_HL';
export const ORDER_BY_PRICE_LH='ORDER_BY_PRICE_LH'
